### ISSUE TITLE
Union throws Exception even though it shoudn't

### ISSUE THREAD

**Issue by TimurKr** [cyrax111/range_type#1]
I am running union on 2 `DateTimeRange`s. They do not have an overlap, as they share one of the bounds. The upper bound of one of them is the same as the lower bound of the other, but with the exception, that one of them is `includive` and the other one is `exclusive`. I believe that this operation should result in a `DateTimeRange` spanning both of these ranges, but instead I get an Exception.  

The `.union` method uses the `.overlap` method, which in this case returns no overlap, which than results in `exception`, even whough the resulting union would be contigous.

The method of checking if there is overlap and throwing an exception if not simply doesn't allow for making the union operation on 2 non-overlaping adjecent ranges, which I believe it should.

**Comment by cyrax111** [comment]
Could you please write the part of the code which throws an exception?

**Comment by TimurKr** [comment]
Sure, here is an example:

```dart
DateTimeRange dateRange1 = DateTimeRange.parse('[2022-07-01, 2022-08-01)');
DateTimeRange dateRange2 = DateTimeRange.parse('[2022-08-01, 2022-09-01)');

print(dateRange1.union(dateRange2)); //throws exception
```

**Comment by cyrax111** [comment]
Fixed. 😄

**Comment by cyrax111** [comment]
@TimurKr is it working for you now?
